# NFL field constants
FIELD_LENGTH = 120.0
FIELD_WIDTH = 53.3
FIELD_MARGIN = 0.0
END_ZONE_WIDTH = 10.0
END_ZONE_COLOR = "#85b034"
YARD = 1.0
YARD_LINE_STEP = 5.0
FIELD_COLOR = "#85b034"
BORDER_LINE_COLOR = "#FFFFFF"
BORDER_LINE_WIDTH = 3.0
YARD_LINE_COLOR = "#FFFFFF"
YARD_LINE_WIDTH = 2.0
HASH_MARK_LENGTH = 1.0
HASH_MARK_SEPARATION = 6.0
CONVERSION_LINE_DIST = 2.0
CONVERSION_LINE_LENGTH = 3.0
ANNOTATION_SIZE = 20.0
ANNOTATION_COLOR = "#FFFFFF"
ANNOTATION_SEPARATION = 4.0

# display constants
SCALE = 10.0
